github.com:
    users:
        chisuhua:
            oauth_token: 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
    git_protocol: https
    user: chisuhua
    oauth_token: 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
